project_tracker/project_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls', namespace='tasks')),
    path('quality_control/', include('quality_control.urls', namespace='quality_control')),
]

project_tracker/tasks/urls.py
from django.urls import path
from tasks import views

app_name = 'tasks'

urlpatterns = [ # функциональные представления
#   path('', views.index),
#   path('projects/', views.projects_list, name='projects_list'),
#   path('projects/<int:project_id>/', views.project_detail, name='project_detail'),
#   path('projects/<int:project_id>/tasks/<int:task_id>/', views.task_detail, name='task_detail'),
#   path('project/new/', views.create_project, name='create_project'),
#   path('projects/<int:project_id>/add_task/', views.add_task_to_project, name='add_task_to_project'),
#   path('projects/<int:project_id>/tasks/<int:task_id>/update', views.update_task, name='update_task'),
#   path('projects/<int:project_id>/update', views.update_project, name='update_project'),
#   path('projects/<int:project_id>/delete/', views.delete_project, name='delete_project'),
#   path('projects/<int:project_id>/tasks/<int:task_id>/delete', views.delete_task, name='delete_task'),

    path('', views.IndexView.as_view(), name='index'), # классовые представления

    path('project/create/', views.ProjectCreateView.as_view(), name='create_project'),
    path('projects/', views.ProjectsListView.as_view(), name='projects_list'),
    path('projects/<int:project_id>/', views.ProjectDetailView.as_view(), name='project_detail'),

    path('projects/<int:project_id>/tasks/<int:task_id>/', views.TaskDetailView.as_view(), name='task_detail'),
    path('projects/<int:project_id>/add_task/', views.TaskCreateView.as_view(), name='add_task_to_project'),

    path('projects/<int:project_id>/tasks/<int:task_id>/update', views.TaskUpdateView.as_view(), name='update_task'),
    path('projects/<int:project_id>/update', views.ProjectUpdateView.as_view(), name='update_project'),

    path('projects/<int:project_id>/delete/', views.ProjectDeleteView.as_view(), name='delete_project'),
    path('projects/<int:project_id>/tasks/<int:task_id>/delete/', views.TaskDeleteView.as_view(), name='delete_task'),
]

project_tracker/templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale = 1.0">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <!-- общий заголовок для всех страниц-->
        <h1> Проект project-tracker </h1>
    </header>
    {% include 'base/nav.html' %}
    <main>
        {% block content %}
        <!-- основное содержимое страницы -->
        {% endblock %}
    </main>

    <footer>
        <!-- общий футер для всех страниц -->
    </footer>
</body>
</html>

project_tracker/templates/base/nav.html
 <nav>
        <!-- навигационное меню -->
        <a href="{% url 'tasks:index' %}">Приложение tasks</a>
            <br>
        <a href="{% url 'quality_control:index' %}">Приложение quality_control</a>
        <!-- сцылки -->
 </nav>