project_tracker/project_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls', namespace='tasks')),
    path('quality_control/', include('quality_control.urls', namespace='quality_control')),
]

project_tracker/quality_control/urls.py
from django.urls import path
from . import views

app_name = 'quality_control'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'), # классовые представления

    path('bugs/', views.BugListView.as_view(), name='bug_list'),
    path('bugs/add_bug/', views.BugCreateView.as_view(), name='create_bug'),
    path('bugs/<bug_id>/', views.BugDetailView.as_view(), name='bug_detail'),
    path('bugs/<bug_id>/update/', views.BugUpdateView.as_view(), name='update_bug'),
    path('bugs/<bug_id>/delete/', views.BugDeleteView.as_view(), name='delete_bug'),


    path('features/', views.FeatureRequestListView.as_view(), name='feature_list'),
    path('features/add_feature/', views.FeatureCreateView.as_view(), name='create_feature'),
    path('features/<feature_id>/', views.FeatureRequestDetailView.as_view(), name='feature_id_detail'),
    path('features/<feature_id>/update/', views.FeatureUpdateView.as_view(), name='update_feature'),
    path('features/<feature_id>/delete/', views.FeatureDeleteView.as_view(), name='delete_feature'),







    #сцылки для функциональных представлений (old)
#    path('', views.index, name='quality_control'),
#    path('bugs/', views.bug_list, name='bug_list'),
#    path('bugs/add_bug/', views.create_bug, name='create_bug'),
#    path('bugs/<bug_id>/', views.bug_detail, name='bug_detail'),
#     path('bugs/<bug_id>/update/', views.update_bug, name='update_bug'),
#     path('bugs/<bug_id>/delete/', views.delete_bug, name='delete_bug'),
#
#    path('features/', views.feature_list, name='feature_list'),
#    path('features/add_feature/', views.create_feature, name='create_feature'),
#    path('features/<feature_id>/', views.feature_id_detail, name='feature_id_detail'),
#     path('features/<feature_id>/update/', views.update_feature, name='update_feature'),
#     path('features/<feature_id>/delete/', views.delete_feature, name='delete_feature'),

]

project_tracker/tasks/urls.py
from django.urls import path
from tasks import views

app_name = 'tasks'

urlpatterns = [ # функциональные представления
#   path('', views.index),
#   path('projects/', views.projects_list, name='projects_list'),
#   path('projects/<int:project_id>/', views.project_detail, name='project_detail'),
#   path('projects/<int:project_id>/tasks/<int:task_id>/', views.task_detail, name='task_detail'),
#   path('project/new/', views.create_project, name='create_project'),
#   path('projects/<int:project_id>/add_task/', views.add_task_to_project, name='add_task_to_project'),
#   path('projects/<int:project_id>/tasks/<int:task_id>/update', views.update_task, name='update_task'),
#   path('projects/<int:project_id>/update', views.update_project, name='update_project'),
#   path('projects/<int:project_id>/delete/', views.delete_project, name='delete_project'),
#   path('projects/<int:project_id>/tasks/<int:task_id>/delete', views.delete_task, name='delete_task'),

    path('', views.IndexView.as_view(), name='index'), # классовые представления

    path('project/create/', views.ProjectCreateView.as_view(), name='create_project'),
    path('projects/', views.ProjectsListView.as_view(), name='projects_list'),
    path('projects/<int:project_id>/', views.ProjectDetailView.as_view(), name='project_detail'),

    path('projects/<int:project_id>/tasks/<int:task_id>/', views.TaskDetailView.as_view(), name='task_detail'),
    path('projects/<int:project_id>/add_task/', views.TaskCreateView.as_view(), name='add_task_to_project'),

    path('projects/<int:project_id>/tasks/<int:task_id>/update', views.TaskUpdateView.as_view(), name='update_task'),
    path('projects/<int:project_id>/update', views.ProjectUpdateView.as_view(), name='update_project'),

    path('projects/<int:project_id>/delete/', views.ProjectDeleteView.as_view(), name='delete_project'),
    path('projects/<int:project_id>/tasks/<int:task_id>/delete/', views.TaskDeleteView.as_view(), name='delete_task'),
]

project_tracker/quality_control/models.py
from django.db import models

from tasks.models import Project, Task


class BugReport(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    task = models.ForeignKey(Task,
                             on_delete=models.SET_NULL,
                             null=True,
                             blank=True,)
    STATUS_CHOICES = [
        ("New", "Новая"),
        ("In progress", "В работе"),
        ("Completed", "Завершена"),
    ]
    status = models.CharField(
        max_length=50,
        choices=STATUS_CHOICES,
        default="new",
    )
    PRIORITY_CHOICES = [
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    ]
    priority = models.IntegerField(
        choices=PRIORITY_CHOICES,
        default=1,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class FeatureRequest(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    task = models.ForeignKey(Task,
                             on_delete=models.SET_NULL,
                             null=True,
                             blank=True, )
    STATUS_CHOICES = [
        ("Consideration", "Рассмотрение"),
        ("Accepted", "Принято"),
        ("Declined", "Отклонено"),
    ]
    status = models.CharField(
        max_length=50,
        choices=STATUS_CHOICES,
        default="new",
    )
    PRIORITY_CHOICES = [
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    ]
    priority = models.IntegerField(
        choices=PRIORITY_CHOICES,
        default=1,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

project_tracker/quality_control/forms.py
from django.forms import ModelForm
from .models import BugReport, FeatureRequest


class BugReportForm(ModelForm):
    class Meta:
        model = BugReport
        fields = ['title', 'description', 'status', 'priority', 'project', 'task']


class FeatureRequestForm(ModelForm):
    class Meta:
        model = FeatureRequest
        fields = ['title', 'description', 'status', 'priority', 'project', 'task']

project_tracker/quality_control/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from .forms import BugReportForm, FeatureRequestForm
from .models import BugReport, FeatureRequest


class IndexView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'quality_control/index.html')


class BugListView(ListView):
    model = BugReport
    template_name = 'quality_control/bug_list.html'
    context_object_name = "bug_list"


class FeatureRequestListView(ListView):
    model = FeatureRequest
    template_name = 'quality_control/feature_list.html'
    context_object_name = "feature_list"


class BugDetailView(DetailView):
    model = BugReport
    pk_url_kwarg = 'bug_id'
    template_name = 'quality_control/bug_detail.html'
    context_object_name = 'bug'


class FeatureRequestDetailView(DetailView):
    model = FeatureRequest
    pk_url_kwarg = 'feature_id'
    template_name = 'quality_control/feature_id_detail.html'
    context_object_name = 'feature'


class BugCreateView(CreateView):
    model = BugReport
    form_class = BugReportForm
    template_name = 'quality_control/bug_report_form.html'
    success_url = reverse_lazy('quality_control/bug_list')

    def from_valid(self, form):
        form.instance.project = get_object_or_404(BugReport, pk=self.kwargs['bug_id'])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('quality_control:bug_list')


class FeatureCreateView(CreateView):
    model = FeatureRequest
    form_class = FeatureRequestForm
    template_name = 'quality_control/feature_request_form.html'

    def from_valid(self, form):
        form.instance.project = get_object_or_404(FeatureRequest, pk=self.kwargs['feature_id'])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('quality_control:feature_list')


class BugUpdateView(UpdateView):
    model = BugReport
    form_class = BugReportForm
    template_name = 'quality_control/bug_update.html'
    pk_url_kwarg = 'bug_id'
    success_url = reverse_lazy('quality_control:bug_list')


class FeatureUpdateView(UpdateView):
    model = FeatureRequest
    form_class = FeatureRequestForm
    template_name = 'quality_control/feature_update.html'
    pk_url_kwarg = 'feature_id'
    success_url = reverse_lazy('quality_control:feature_list')


class BugDeleteView(DeleteView):
    model = BugReport
    template_name = 'quality_control/bug_confirm_delete.html'
    pk_url_kwarg = 'bug_id'
    success_url = reverse_lazy('quality_control:bug_list')
    context_object_name = 'bug'


class FeatureDeleteView(DeleteView):
    model = FeatureRequest
    pk_url_kwarg = 'feature_id'
    success_url = reverse_lazy('quality_control:feature_list')
    template_name = 'quality_control/feature_confirm_delete.html'
    context_object_name = 'feature'


# def index(request):
#     bug_list_url = reverse('quality_control:bug_list')
#     feature_list_url = reverse('quality_control:feature_list')
#     html = f"<h1> Система контроля качества </h1> " \
#            f"<a href='{bug_list_url}'> Список всех багов"   \
#            f"<br> <a href='{feature_list_url}'> Запросы на улучшение"
#     return HttpResponse(html)

# def bug_list(request):
#     return HttpResponse('Cписок отчетов об ошибках')
#
# def bug_list(request):
#     bug = BugReport.objects.all()
#     return render(request, 'quality_control/bug_list.html', {'bug_list': bug})

# def feature_list(request):
#     return HttpResponse('Список запросов на улучшение')

# def feature_list(request):
#     features = FeatureRequest.objects.all()
#     return render(request, 'quality_control/feature_list.html', {'feature_list': features})
# #
# def bug_detail(request, bug_id):
#     return HttpResponse(f'Детали бага {bug_id}')
#
# def feature_id_detail(request, feature_id):
#     return HttpResponse(f'Детали улучшения {feature_id}')

# def bug_list(request):
#     bugs = BugReport.objects.all()
#     bugs_html = '<h1> Список ошибок </h1><ul>'
#     for bug in bugs:
#         bugs_html += f'<li><a href="{bug.id}/">{bug.title} | Status:{bug.status}</a></li>'
#     bugs_html += "</ul>"
#     return HttpResponse(bugs_html)

# def feature_list(request):
#     features = FeatureRequest.objects.all()
#     features_html = '<h1> Список запросов на улучшение </h1><ul>'
#     for feature in features:
#         features_html += f'<li><a href="{feature.id}/">{feature.title} | Status:{feature.status}</a></li>'
#     features_html += "</ul>"
#     return HttpResponse(features_html)

#def bug_detail(request, bug_id):
#    bug = get_object_or_404(BugReport, id=bug_id)
#    response_html = f'<h1>{bug.title}</h1><p>{bug.description}</p>'
#    return HttpResponse(response_html)

#def feature_id_detail(request, feature_id):
#    feature = get_object_or_404(FeatureRequest, id=feature_id)
#    response_html = f'<h1>{feature.title}</h1><p>{feature.description}</p>'
#    return HttpResponse(response_html)

# class IndexView(View):
#     def get(self, request, *args, **kwargs):
#         # bug_list_url = reverse('quality_control:bug_list')
#         # feature_list_url = reverse('quality_control:feature_list')
#         # html = f"<h1> Система контроля качества </h1> " \
#         #         f"<a href='{bug_list_url}'> Список всех багов"   \
#         #         f"<br> <a href='{feature_list_url}'> Запросы на улучшение"
#         return render(request, 'quality_control/index.html')

# class BugListView(ListView):
#     model = BugReport
#
#     def get(self, request,  *args, **kwargs):
#         bugs = self.get_queryset()
#         bugs_html = '<h1> Список ошибок </h1><ul>'
#         for bug in bugs:
#             bugs_html += f'<li><a href="{bug.id}/">{bug.title} | Status:{bug.status}</a></li>'
#         bugs_html += "</ul>"
#         return HttpResponse(bugs_html)
#
# class FeatureRequestListView(ListView):
#     model = FeatureRequest
#
#     def get(self, request, *args, **kwargs):
#         features = self.get_queryset()
#         features_html = '<h1> Список запросов на улучшение </h1><ul>'
#         for feature in features:
#             features_html += f'<li><a href="{feature.id}/">{feature.title} | Status:{feature.status}</a></li>'
#         features_html += "</ul>"
#         return HttpResponse(features_html)
#
# class BugDetailView(DetailView):
#     model = BugReport
#     pk_url_kwarg = 'bug_id'
#     def get(self, request, *args, **kwargs):
#         self.object = self.get_object()
#         bug = self.object
#         response_html = f'<h1>{bug.title}</h1>'\
#                         f'<p>Related project: {bug.project.name}</p>' \
#                         f'<p>Related task: {bug.task.name} | Related task status: {bug.task.status}</p>' \
#                         f'<p>Status: {bug.status}</p>' \
#                         f'<p>Priority: {bug.priority}</p>' \
#                         f'<p>Description: {bug.description}</p>'
#         return HttpResponse(response_html)
#
#
# class FeatureRequestDetailView(DetailView):
#     model = FeatureRequest
#     pk_url_kwarg = 'feature_id'
#     def get(self, request, *args, **kwargs):
#         self.object = self.get_object()
#         feature = self.object
#         response_html = f'<h1>{feature.title}</h1>' \
#                         f'<p>Related project: {feature.project.name}</p>' \
#                         f'<p>Related task: {feature.task.name} Related task status: {feature.task.status}</p>' \
#                         f'<p>Status: {feature.status}</p>' \
#                         f'<p>Priority: {feature.priority}</p>'  \
#                         f'<p>Description: {feature.description}</p>'
#         return HttpResponse(response_html)

# def create_bug(request):
#     if request.method == 'POST':
#         form = BugReportForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('quality_control:bug_list')
#     else:
#         form = BugReportForm()
#     return render(request, 'quality_control/create_bug.html', {'form': form})

# def create_request(request):
#     if request.method == 'POST':
#         form = FeatureRequestForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('quality_control:feature_list')
#     else:
#         form = FeatureRequestForm()
#     return render(request, 'quality_control/create_request.html', {'form': form})

# def update_bug(request, bug_id):
#     bug = get_object_or_404(BugReport, pk=bug_id)
#     if request.method == 'POST':
#         form = BugReportForm(request.POST, instance=bug)
#         if form.is_valid():
#             form.save()
#             return redirect('quality_control:bug_detail', bug_id=bug.id)
#     else:
#         form = BugReportForm(instance=bug)
#     return render(request, 'quality_control/bug_update.html', {'form': form, 'bug': bug})
#
# def update_feature(request, feature_id):
#     feature = get_object_or_404(FeatureRequest, pk=feature_id)
#     if request.method == 'POST':
#         form = FeatureRequestForm(request.POST, instance=feature)
#         if form.is_valid():
#             form.save()
#             return redirect('quality_control:feature_id_detail', feature_id=feature.id)
#     else:
#         form = FeatureRequestForm(instance=feature)
#     return render(request, 'quality_control/feature_update.html', {'form': form, 'feature': feature})
#
# def delete_bug(request, bug_id):
#     bug = get_object_or_404(BugReport, pk=bug_id)
#     bug.delete()
#     return redirect('quality_control:bug_list')
#
# def delete_feature(request, feature_id):
#     feature = get_object_or_404(FeatureRequest, pk=feature_id)
#     feature.delete()
#     return redirect('quality_control:feature_list')

project_tracker/quality_control/templates/quality_control/bug_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Удаление баг-репорта</h1>
    <p>Вы уверены, что хотите удалить баг-репорт "{{ bug.title }}"?</p>

    <form action="{% url 'quality_control:delete_bug' bug.id%}" method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
        <a href="{% url 'quality_control:bug_detail' bug.id%}">Отмена</a>
    </form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/bug_detail.html
{% extends 'base/base.html' %}

{% block content %}

    <h1> {{ bug.title }}</h1>
    <p><a href="{% url 'quality_control:update_bug' bug.id %}">Изменить баг-репорт</a></p>
    <p><a href="{% url 'quality_control:delete_bug' bug.id %}" onclick="return confirm('Вы уверены, что хотите удалить этот баг-репорт?');">Удалить баг-репорт</a></p>
    <p> Related project: <a href="{% url 'tasks:project_detail' bug.project.id %}">{{bug.project.name}}</a></p>
    <p> Related task: {{bug.task.name}}</p>
    <p> Description: {{  bug.description }} </p>
    <p> Status: {{ bug.status }}</p>
    <p> Priority: {{ bug.priority }}</p>

{% endblock %}

project_tracker/quality_control/templates/quality_control/bug_list.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Список ошибок</h1>
            <!-- Ссылка на создание нового бага -->
    <p><a href="{% url 'quality_control:create_bug' %}">Создать новый баг-репорт</a></p>
    <ul>
        {% for bug in bug_list %}
            <li><a href="{% url 'quality_control:bug_detail' bug.id%}">{{ bug.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

project_tracker/quality_control/templates/quality_control/bug_report_form.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Добавить новый баг-репорт </h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Создать репорт</button>
    </form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/bug_update.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Изменение бага: {{ bug.title }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/feature_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Удаление запроса</h1>
    <p>Вы уверены, что хотите удалить запрос "{{ feature.title }}"?</p>

    <form action="{% url 'quality_control:delete_feature' feature.id%}" method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
        <a href="{% url 'quality_control:feature_id_detail' feature.id%}">Отмена</a>
    </form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/feature_id_detail.html
{% extends 'base/base.html' %}

{% block content %}
    <h1> {{ feature.title }}</h1>
    <p><a href="{% url 'quality_control:update_feature' feature.id %}">Изменить запрос на улучшение</a></p>
    <p><a href="{% url 'quality_control:delete_feature' feature.id %}">Удалить запрос на улучшение</a></p>
    <p> Related project: <a href="{% url 'tasks:project_detail' feature.project.id %}">{{feature.project.name}}</a></p>
    <p> Related task: {{feature.task.name}}</p>
    <p> Description: {{ feature.description }}</p>
    <p> Status:{{ feature.status }}</p>
    <p> Priority: {{ feature.priority }}</p>


{% endblock %}

project_tracker/quality_control/templates/quality_control/feature_list.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Список запросов на улучшение</h1>
    <p><a href="{% url 'quality_control:create_feature' %}">Создать новый запрос на улучшение</a></p>
    <ul>
        {% for feature in feature_list %}
            <li><a href="{% url 'quality_control:feature_id_detail' feature.id%}">{{ feature.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

project_tracker/quality_control/templates/quality_control/feature_request_form.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Добавить новый запрос на улучшение</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Создать запрос</button>
    </form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/feature_update.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Изменение запроса на улучшение: {{ feature.title }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/index.html
{% extends 'base/base.html' %}

{% block content %}
        <h1>Страница приложения quality control</h1>
        <a href="{% url 'quality_control:bug_list' %}">Список ошибок</a>
        <a href="{% url 'quality_control:feature_list' %}">Список запросов на улучшение</a>
{% endblock %}